name: Update Link Previews
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  update_screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: link-previews
